// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/工作/Demo/aaa-web/web-base/src/models/global';
import model_2 from '/Users/工作/Demo/aaa-web/web-base/src/models/theme';
import model_3 from '/Users/工作/Demo/aaa-web/web-base/src/.umi-production/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'global', model: model_1 },
model_2: { namespace: 'theme', model: model_2 },
model_3: { namespace: '@@initialState', model: model_3 },
} as const
